### ISSUE TITLE
Hitboxes of Blocks Dont Turn

### ISSUE THREAD

**Issue by MrFoolthe2st** [quattage/extended-tables#8]
(Running on this release https://github.com/quattage/mechano/releases/latest with forge 47.1.43 on 1.20.1 with Create 0.5.1.d)
Hitboxes don't seem to turn on certain objects such as:
- Connectors of all types
- Diagonal Girders*

The turning seems to only happen on one axis, but I'm not sure which one
![2024-05-23_21 03 25](https://github.com/quattage/mechano/assets/150611620/40237e2f-b4f2-4585-9005-6b2b4db28ad7)
![2024-05-23_21 04 16](https://github.com/quattage/mechano/assets/150611620/f2d78bca-63f3-4909-889a-4c2e7f366367)

*Diagonal Girders' hitboxes turn correctly but their model doesn't
(this is my first issue report ever so sorry if it's bad)

**Comment by quattage** [comment]
All of this stuff has either been removed or solved in the dev branch already, (except for girders i think those are still reversed) i'll be making a new release soon but for right now the only one available is almost a year old
